### ISSUE TITLE
Public easy to remember URL for material

### ISSUE THREAD

**Issue by kyyberi** [mniinio/APIOps-cycles#1]
To make it easy to market, I suggest that we create subdomain for this. 

cycles.apiops.net which points to Github pages.

**Comment by mniinio** [comment]
Absolutely, please register now

**Comment by kyyberi** [comment]
I'll handle this.

**Comment by kyyberi** [comment]
Added CNAME file to root. It contains just the subdomain

**Comment by kyyberi** [comment]
Requested DNS changes to be done asap. Until the changes are done, pages are not available. Fix is to remove domain file (CNAME) until the DNS setting is done.

**Comment by kyyberi** [comment]
I'll take it away until DNS is clear

**Comment by kyyberi** [comment]
Done and works. Closing
